#!/bin/sh
set -e

if [ ! -f /var/lib/powerdns/bind-dnssec-db.sqlite3 ]; then
    pdnsutil create-bind-db /var/lib/powerdns/bind-dnssec-db.sqlite3
fi
chown -R pdns:pdns /var/lib/powerdns
chmod 700 /var/lib/powerdns

exec /usr/sbin/pdns_server --daemon=no --guardian=no --disable-syslog
