#!/bin/sh
set -e

mkdir -p /var/lib/powerdns
if [ ! -f /var/lib/powerdns/bind-dnssec-db.sqlite3 ]; then
    pdnsutil create-bind-db /var/lib/powerdns/bind-dnssec-db.sqlite3
fi
chown -R pdns:pdns /var/lib/powerdns
chmod 700 /var/lib/powerdns

chmod 755 /etc/pdns
chmod 644 /etc/pdns/*

exec /usr/sbin/pdns_server --daemon=no --guardian=no --disable-syslog
